### ISSUE TITLE
Add support for travis-ci to deploy to rubygems

### ISSUE THREAD

**Issue by ronen** [SchemaPlus/schema_dev#18]
Each gem's `schema_dev.yml` file should allow an optional field:

```yaml
travis_rubygems_key: O6ppogYENdh7TprJbbW5OkKMEUAdZioZOWUEdm84+B/6hzYpPbvDsqrX+NbOk8f94r7pllxwribJypLN3VmIj5DDKKBMWW4YSfUQFpN6S0oVh2zlu4cINeEs8IhxP2I8rHesr0T6LN0j7CskImO5E1sKwrTL1E8EKLuUASK658I=
```

If present, schema_dev would include this magic in the `.travis.yml` file, telling Travis to deploy to rubygems whenever a tagged version passes the tests.

```yaml
deploy:
  provider: rubygems
  api_key:
    secure: O6ppogYENdh7TprJbbW5OkKMEUAdZioZOWUEdm84+B/6hzYpPbvDsqrX+NbOk8f94r7pllxwribJypLN3VmIj5DDKKBMWW4YSfUQFpN6S0oVh2zlu4cINeEs8IhxP2I8rHesr0T6LN0j7CskImO5E1sKwrTL1E8EKLuUASK658I=
  gem: schema_plus_core
  on:
    tags: true
    repo: SchemaPlus/schema_plus_core
```
(Of course using the current gem's name for the repo field.)  See [Travis-CI RubyGems Deployment](https://docs.travis-ci.com/user/deployment/rubygems/).

Probably the easiest way to generate the key would be for a rubygems owner of the gem to run `travis setup rubygems` which would add all the above to the `.travis.yml`.  Then copy and paste the key to the `schema_dev.yml` file; then run `schema_dev freshen`
